// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIN_N_tk-jhq8L3QLZzFfQfJyCd_u0cA',
    appId: '1:62907413904:web:df9c686e5d635798942f15',
    messagingSenderId: '62907413904',
    projectId: 'videocallsample-6a521',
    authDomain: 'videocallsample-6a521.firebaseapp.com',
    storageBucket: 'videocallsample-6a521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg0voK_qA--ee0Rlf5cXvcG-Gfjdwkc04',
    appId: '1:62907413904:android:4958e3d0a2326874942f15',
    messagingSenderId: '62907413904',
    projectId: 'videocallsample-6a521',
    storageBucket: 'videocallsample-6a521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaaeR-ANTcitinEINdgE6mznhMxd6N9gg',
    appId: '1:62907413904:ios:ff654f61cf28f2d4942f15',
    messagingSenderId: '62907413904',
    projectId: 'videocallsample-6a521',
    storageBucket: 'videocallsample-6a521.firebasestorage.app',
    iosBundleId: 'com.example.videocallsample',
  );
}
